# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bkM_7KT9R9qnlymiSD1pZF7uQErRZ5IF
"""

import pandas as pd

df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'), 'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})

df

df_a = df[df['grps'] == 'a']
df_a

df_a = df_a.sort_values(by='vals', ascending=False)
df_A = df_a.head(3)
df_A

df_b = df[df['grps'] == 'b']
df_b

df_b = df_b.sort_values(by='vals', ascending=False)
df_B = df_b.head(3)
df_B

df_c = df[df['grps'] == 'c']
df_c

df_c = df_c.sort_values(by='vals', ascending=False)
df_C = df_c.head(3)
df_C

